# Generated by Django 2.1.7 on 2020-10-12 18:12

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=70, unique=True, verbose_name='Email')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Enter valid contact number with country code', max_length=128, region=None)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('dob', models.DateField(max_length=8, null=True, verbose_name='Date of Birth')),
                ('hq', models.CharField(choices=[('No formal education', 'No formal education'), ('Primary Education', 'Primary Education'), ('Secondary Education', 'Secondary Education'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree")], max_length=50, null=True, verbose_name='Highest Qualification')),
                ('pro_pic', models.ImageField(blank=True, default='default_pic.jpg', null=True, upload_to='profile_pictures', verbose_name='Profile Picture')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Email Verification')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('transactions', models.ManyToManyField(blank=True, to='payu.Transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
