# Generated by Django 2.1.7 on 2020-10-12 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Course Calendar',
                'verbose_name_plural': 'Course Calendar',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('batch_no', models.CharField(max_length=3, verbose_name='Batch No')),
                ('location', models.CharField(max_length=20, verbose_name='Location')),
                ('image', models.ImageField(upload_to='Gallery/')),
                ('position', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Gallery',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('slug', models.SlugField()),
                ('duration', models.CharField(max_length=10, null=True)),
                ('image', models.ImageField(upload_to='CourseImages/')),
                ('online_course', models.NullBooleanField()),
                ('expiry', models.DurationField(help_text='Eg: 30 days, enter any number of days for offline course', verbose_name='Course Expiry')),
                ('description1', models.CharField(blank=True, max_length=50, null=True)),
                ('description2', models.CharField(blank=True, max_length=50, null=True)),
                ('description3', models.CharField(blank=True, max_length=50, null=True)),
                ('description4', models.CharField(blank=True, max_length=50, null=True)),
                ('description5', models.CharField(blank=True, max_length=50, null=True)),
                ('test_link', models.CharField(blank=True, max_length=250, null=True, verbose_name='Test Link')),
                ('text_book', models.FileField(blank=True, null=True, upload_to='Text Book/', verbose_name='Text Book')),
            ],
            options={
                'verbose_name': 'COURSE',
                'verbose_name_plural': 'COURSES',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=120)),
                ('position', models.IntegerField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='LessonThumb/')),
                ('video_file', models.FileField(upload_to='Lesson Videos/')),
                ('description1', models.CharField(blank=True, max_length=50, null=True)),
                ('description2', models.CharField(blank=True, max_length=50, null=True)),
                ('description3', models.CharField(blank=True, max_length=50, null=True)),
                ('description4', models.CharField(blank=True, max_length=50, null=True)),
                ('description5', models.CharField(blank=True, max_length=50, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Item')),
            ],
            options={
                'verbose_name': 'Course Lesson',
                'verbose_name_plural': 'Course Lessons',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('invoice', models.FileField(blank=True, null=True, upload_to='Invoice/')),
            ],
            options={
                'verbose_name': 'ORDER',
                'verbose_name_plural': 'ORDERS',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Item', verbose_name='Course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'COURSE PURCHASED',
                'verbose_name_plural': 'COURSES PURCHASED',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Organization')),
                ('location', models.CharField(max_length=30, verbose_name='Location')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.CreateModel(
            name='PilotList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Pilot Name')),
                ('organization', models.CharField(max_length=50, verbose_name='Organization')),
                ('date', models.DateField()),
                ('certificate_no', models.CharField(max_length=20, verbose_name='Certificate Number')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Item')),
            ],
            options={
                'verbose_name': 'Pilot',
                'verbose_name_plural': 'Pilot List',
            },
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone No.')),
                ('query', models.TextField(verbose_name='Query')),
            ],
            options={
                'verbose_name': 'Query',
                'verbose_name_plural': 'Queries',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Student Name')),
                ('location', models.CharField(max_length=20, verbose_name='Location')),
                ('certificate_no', models.CharField(max_length=20, verbose_name='Certificate No')),
                ('video_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='app.OrderItem'),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payu.Transaction'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gallery',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Item'),
        ),
    ]
