# Generated by Django 2.1.7 on 2020-10-12 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='test_link',
        ),
        migrations.RemoveField(
            model_name='item',
            name='text_book',
        ),
    ]
